CREATE TABLE `intake_data` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`inquiry_id` integer NOT NULL,
	`partner_name` text,
	`best_address` text,
	`ceremony_start_time` text,
	`reception_start_time` text,
	`getting_ready_location` text,
	`reception_venue` text,
	`guest_count` text,
	`first_look` text,
	`send_off_type` text,
	`must_capture_moments` text,
	`family_portrait_list` text,
	`bridal_party_size` text,
	`cultural_traditions` text,
	`planned_surprises` text,
	`add_ons` text,
	`engagement_session` text,
	`photography_style` text,
	`must_have_shots` text,
	`shots_to_avoid` text,
	`color_palette` text,
	`inspiration_links` text,
	`self_conscious_areas` text,
	`wedding_planner` text,
	`coordinator` text,
	`dj` text,
	`officiant` text,
	`videographer` text,
	`venue_contact` text,
	`day_of_contact` text,
	`parking_notes` text,
	`getting_ready_room_notes` text,
	`venue_restrictions` text,
	`photographer_meals` text,
	`legal_name_1` text,
	`legal_name_2` text,
	`billing_address` text,
	`payment_method` text,
	`payment_plan` text,
	`completed_at` text,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE `inquiries` ADD `portal_token` text;--> statement-breakpoint
ALTER TABLE `inquiries` ADD `referral_source` text;